Admin courses
MSWE-Teaching-Management-Capstone/TeachingManagementWebApplication pull request #23
Opened 2022-11-19 05:37 UTC by yuchesu

Finish teaching point calculation logic

2022-11-19 19:10 UTC, jjlock commented
Reviewing this now.

2022-11-19 19:35 UTC, jjlock requested changes

2022-11-19 19:35 UTC, jjlock commented on management_app/views/points.py
> +        rows = db.execute(sql_statement).fetchall()
Using format strings to create a SQL statement is vulnerable to SQL injection. Use `db.execute` to create the SQL statement.

2022-11-22 00:10 UTC, yrfang requested changes

2022-11-22 00:10 UTC, yrfang commented on management_app/views/points.py
>      ).fetchone()
I was wondering if we need to check `row` is None when there is no matched `course_title_id` when uploading the teaching_schedule file? Only when there is a valid course_title_id to match teaching_schedule, we process 'units' and 'course_level' to update enrollment and further calculate the new `teaching_point_val`?

2022-11-22 00:10 UTC, yrfang commented on management_app/views/course.py
> +        calculate_combined_classes_and_update_scheduled_teaching(rows_dict)
Somehow when I uploaded a new schedule_teaching_point file with a new enrollment number, I had an issue with the `TypeError: 'dict_keys' object is not subscriptable` error. Let's check this a bit offline.

2022-11-22 00:29 UTC, yrfang commented on management_app/views/course.py
> +        calculate_combined_classes_and_update_scheduled_teaching(rows_dict)
For `calculate_combined_classes_and_update_scheduled_teaching` function, would it call when`rows_dict` is not empty? So it is feasible to process keys from `rows_dict.keys()`.

2022-11-22 00:55 UTC, yrfang approved these changes
The key error of `rows_dict` has been fixed.
```
keys = list(rows_dict.keys())
```

2022-11-22 01:02 UTC, yrfang commented
For SQL injection, the new commit includes validation to prevent injection vulnerability, so I'm going to merge this PR.

2022-11-22 01:02 UTC, merged